### ISSUE TITLE
user-init-file set to .../lisp/progmodes/compile.el.gz

### ISSUE THREAD

**Issue by phil-s** [emacscollective/auto-compile#33] opened 2023-09-21 13:46 UTC
If I have `init.el` byte-compiled, and `init.el` is newer than `init.elc`, then I'm seeing the following in \*Messages\*:

```
Recompiling /home/phil/.emacs.d.sandboxes/autocomp/HOME/.emacs.d/init.el...
uncompressing compile.el.gz...done
Wrote /home/phil/.emacs.d.sandboxes/autocomp/HOME/.emacs.d/init.elc
Recompiling /home/phil/.emacs.d.sandboxes/autocomp/HOME/.emacs.d/init.el...done
```

And `user-init-file` has ended up being set to `"/home/phil/emacs/29.x.nc/usr/local/share/emacs/29.1.50/lisp/progmodes/compile.el.gz"`

(n.b. The emacs config path is on account of `env HOME="/home/phil/.emacs.d.sandboxes/autocomp/HOME"`, and `/home/phil/emacs/29.x.nc/usr/local` is the configured `--prefix` for this build of Emacs.)

For testing I've created a new config with auto-compile installed and the following init files:

```el
;; early-init.el:
;; Recompile .elc files automatically whenever necessary. Enable this early.
(add-to-list 'load-path (expand-file-name "elpa/auto-compile-20230901.1232" user-emacs-directory))
(require 'auto-compile)
(auto-compile-on-save-mode 1)
(auto-compile-on-load-mode 1)
```

```el
;; init.el
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages '(auto-compile)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

From a shell within that config directory, this reproduces the issue in Emacs 29:
```sh
$ emacs --batch -f batch-byte-compile init.el
$ touch init.el && emacs --init-directory="$(pwd)" --eval="(message \"%s\" user-init-file)"
```

I've been using auto-compile for many years (it's been exceedingly useful) and wasn't aware of having had any issues with it.  I've updated that package for the purposes of testing this, but the version I was using before today had a 2014 copyright notice.  The new version did not affect the problem behaviour for me.

I do not typically have a byte-compiled `init.elc` file though, and further testing shows that I can also reproduce this in Emacs 28.2 and Emacs 27.2.  The latter gives me a user-init-file of: "/home/phil/emacs/27.2/usr/local/share/emacs/27.2.50/lisp/progmodes/compile.elc"

I also have 26.3 and 25.3 installed, and the issue does not occur in either of those.  The new auto-compile version didn't work in 25.3 so I switched back to the old one, which I've identified as: https://raw.githubusercontent.com/emacscollective/auto-compile/822c6fc0ffc84bd567482132e1bcb61fc09a5300/auto-compile.el

(n.b. With the `--init-directory` option being new to 29.1, my test process was a little different for the older versions.)

I became aware of this problem while using `emacs -Q` when it suddenly acquired some of the custom faces from my config!  This turned out to be because my customized user options had been written to the end of `compile.el.gz` and so were being applied if that library was loaded (which had happened when I ran M-x rgrep).  (This also explained why I'd previously felt that customized settings were sometimes being lost, as starting Emacs would only read the settings which had made it into the init.el file before this all started happening.)

FWIW, I initially put the following into init.el:

```el
(add-variable-watcher 'user-init-file 'my-var-debug)
(defun my-var-debug (symbol newval operation where)
  (message "DEBUG: variable changed: %S %S %S %S"
           symbol newval operation where)
  (debug))
```

And got the following backtrace:

```plain
Debugger entered: nil
  my-var-debug(user-init-file "/home/phil/emacs/29.x.nc/usr/local/share/emacs/29.1.50/lisp/progmodes/compile.el.gz" set nil)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0x1898d43e01bfb6af>) #f(compiled-function () #<bytecode -0x1f3c61addc0b8a75>) t)
  command-line()
  normal-top-level()
```

Getting a backtrace has been inconsistent while trying to debug this though.

[Emacs bug #59358](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=59358) was the only similar bug I found when searching, but as that involves native-compilation and I can see this bug with Emacs 27, I don't think that's relevant.

I was in the process of `M-x report-emacs-bug` when I connected it to auto-compile, so I've switched to reporting it here to find out what you think first.  I'm happy to take it back to bug-gnu-emacs if you think it's an Emacs bug.

**Comment by tarsius** [comment] 2023-09-23 20:33
I'm able to reproduce. I was also able in the regular location, without `--init-directory`, using very simple `*init.el` files, but also with my own files.

I was able to "fix" it by adding `(require 'compile)` in `early-init.el`.

**Comment by tarsius** [comment] 2024-01-02 14:19
> I'm happy to take it back to bug-gnu-emacs if you think it's an Emacs bug.

Please do.

I don't understand what is happening. I have a hunch that it might have something to do with the value of `load-file-name` somehow ending up being wrong at some point, because `auto-compile` changes it in a way / at a time, not expected by Emacs.

**Comment by phil-s** [comment] 2024-03-01 03:40
https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69467

**Comment by tarsius** [comment] 2024-03-04 23:08
I've pushed a fix to the `compile-init` branch. Please give it a try.

**Closed** 2024-03-06 13:26 UTC
